/*
 important*/
(function(c){var b=function(){};b.test=document.createElement("div");b.randomiseArray=function(a){var b=[],d=[],c;for(c=0;c<a;c++)b[c]=c;for(c=0;c<a;c++){var l=Math.round(Math.random()*(b.length-1));d[c]=b[l];b.splice(l,1)}return d};b.sortArray=function(a,b){var d,c=a.length,f=[];for(d=0;d<c;d++)f[d]=a[b[d]];return f};b.keysrt=function(a,b,d){var c=1;d&&(c=-1);return a.sort(function(a,d){var f=a[b],z=d[b];return c*(f<z?-1:f>z?1:0)})};b.keysrt2=function(a,b,d,c){var f=1;c&&(f=-1);return a.sort(function(a,
c){var z=a[b][d],l=c[b][d];return f*(z<l?-1:z>l?1:0)})};b.isEmpty=function(a){return 0==a.replace(/^\s+|\s+$/g,"").length};b.checkKey=function(a){return a.replace(/[^0-9a-zA-Z_-\s(),]/g,"")};b.stripSlashes=function(a){a=a.replace(/\\/g,"/");a=a.replace(/\\'/g,"'");a=a.replace(/\\"/g,'"');a=a.replace(/\\0/g,"\x00");return a=a.replace(/\\\\/g,"\\")};b.filterAllowedChars=function(a){var b=a.length,d="",c;for(c=0;c<b;c++){var l=a.charAt(c).toLowerCase();"\\"==l&&(l="/");var q=l.charCodeAt(0);if(97<=q&&
122>=q||48<=q&&57>=q||0<="_-".indexOf(l))d+=l}return d};b.selectText=function(a){var b=document;a=b.getElementById(a);if(b.body.createTextRange)b=b.body.createTextRange(),b.moveToElementText(a),b.select();else if(c.getSelection){var d=c.getSelection();b=b.createRange();b.selectNodeContents(a);d.removeAllRanges();d.addRange(b)}};b.getVideoFormat=function(){var a=document.createElement("video");if(a.canPlayType){if("probably"==a.canPlayType("video/mp4")||"maybe"==a.canPlayType("video/mp4"))var b=".mp4";
else if("probably"==a.canPlayType("video/ogg")||"maybe"==a.canPlayType("video/ogg"))b=".ogg";else if("probably"==a.canPlayType("video/webm")||"maybe"==a.canPlayType("video/webm"))b=".webm";return b}};b.videoSupport=function(){return!!document.createElement("video").canPlayType};b.canPlayVorbis=function(){var a=document.createElement("video");return!(!a.canPlayType||!a.canPlayType('video/ogg; codecs="theora, vorbis"').replace(/no/,""))};b.canPlayMp4=function(){var a=document.createElement("video");
return!(!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"').replace(/no/,""))};b.canPlayWebM=function(){var a=document.createElement("video");return!(!a.canPlayType||!a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/no/,""))};b.audioSupport=function(){return!!document.createElement("audio").canPlayType};b.canPlayMp3=function(){var a=document.createElement("audio");return!(!a.canPlayType||!a.canPlayType("audio/mpeg;").replace(/no/,""))};b.canPlayWav=function(){var a=
document.createElement("audio");return!(!a.canPlayType||!a.canPlayType("audio/wav;").replace(/no/,""))};b.canPlayOgg=function(){var a=document.createElement("audio");return!(!a.canPlayType||!a.canPlayType('audio/ogg; codecs="vorbis"').replace(/no/,""))};b.volumeCanBeSet=function(){var a=document.createElement("audio");if(!a)return!1;a.volume=0;return 0==a.volume?!0:!1};b.hasPointerEvent=function(){return!!c.navigator.msPointerEnabled};b.isMobile=function(){return b.hasPointerEvent&&1<navigator.msMaxTouchPoints?
!0:/Android|webOS|iPhone|iPad|iPod|sony|BlackBerry/i.test(navigator.userAgent)};b.isMac=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("mac")};b.isWin=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("win")};b.isIOS=function(){return navigator.userAgent.match(/(iPad|iPhone|iPod)/g)};b.isAndroid=function(){return-1<navigator.userAgent.indexOf("Android")};b.isiPad=function(){return-1<navigator.userAgent.indexOf("iPad")};b.isiPhoneIpod=function(){var a=navigator.userAgent;
return-1<a.indexOf("iPhone")||-1<a.indexOf("iPod")};b.isSafari=function(){return 0<Object.prototype.toString.call(c.HTMLElement).indexOf("Constructor")};b.isChrome=function(){var a=navigator.userAgent,b=!(0<Object.prototype.toString.call(c.HTMLElement).indexOf("Constructor"))&&"WebkitTransform"in document.documentElement.style;(-1<a.indexOf("iPhone")||-1<a.indexOf("iPod")||-1<a.indexOf("iPad"))&&a.match("CriOS")&&(b=!0);return b};b.isOpera=function(){return!(!c.opera||!c.opera.version)};b.isIE=function(){var a=
c.navigator.userAgent,b=a.indexOf("MSIE ");if(0<b)return parseInt(a.substring(b+5,a.indexOf(".",b)),10);if(0<a.indexOf("Trident/"))return b=a.indexOf("rv:"),parseInt(a.substring(b+3,a.indexOf(".",b)),10);b=a.indexOf("Edge/");return 0<b?parseInt(a.substring(b+5,a.indexOf(".",b)),10):!1};b.parseXML=function(a){if(c.ActiveXObject&&c.GetObject){var b=new ActiveXObject("Microsoft.XMLDOM");b.loadXML(a);return b}if(c.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");throw Error("No XML parser available");
};b.baseUrl=function(){return c.location.href.replace(c.location.hash,"")};b.protocol=function(){return c.location.protocol};b.qualifyURL=function(a){var b=document.createElement("a");b.href=a;return b.href};b.hasLocalStorage=function(){try{return"localStorage"in c&&null!==c.localStorage}catch(a){return!1}};b.validateEmail=function(a){return/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/.test(a)?!0:!1};b.hasDownloadSupport=function(a){return"download"in document.createElement("a")};b.relativePath=function(a){return/^(?:[a-z]+:)?\/\//i.test(a)};
b.getScrollOffsets=function(){if(null!=c.pageXOffset)return{x:c.pageXOffset,y:c.pageYOffset};if("CSS1Compat"==document.compatMode)return{x:document.documentElement.scrollLeft,y:document.documentElement.scrollTop}};b.getViewportSize=function(){return b.hasPointerEvent&&1<navigator.msMaxTouchPoints?{w:document.documentElement.clientWidth||c.innerWidth,h:document.documentElement.clientHeight||c.innerHeight}:b.isMobile?{w:c.innerWidth,h:c.innerHeight}:{w:document.documentElement.clientWidth||c.innerWidth,
h:document.documentElement.clientHeight||c.innerHeight}};b.getViewportMouseCoordinates=function(a){var c=b.getScrollOffsets();return a.touches?{screenX:void 0==a.touches[0]?a.touches.pageX-c.x:a.touches[0].pageX-c.x,screenY:void 0==a.touches[0]?a.touches.pageY-c.y:a.touches[0].pageY-c.y}:{screenX:void 0==a.clientX?a.pageX-c.x:a.clientX,screenY:void 0==a.clientY?a.pageY-c.y:a.clientY}};b.supportCalc=function(){return checkCalc("-webkit-")||checkCalc("-moz-")||checkCalc()};checkCalc=function(a){a=a||
"";var b=document.createElement("div");b.style.cssText=a+"width: calc(1px);";return!!b.style.length};b.supportsTransitions=function(){var a=document.createElement("p").style;return"transition"in a||"WebkitTransition"in a||"MozTransition"in a||"msTransition"in a||"OTransition"in a};b.hasCanvas=function(){return!!document.createElement("canvas")};b.hasFullscreen=function(){return b.test.requestFullscreen||b.test.mozRequestFullScreen||b.test.msRequestFullscreen||b.test.oRequestFullscreen||b.test.webkitRequestFullScreen};
b.preventSelect=function(a){jQuery(a).each(function(){jQuery(this).attr("unselectable","on").css({"-moz-user-select":"none","-webkit-user-select":"none","user-select":"none"}).each(function(){this.onselectstart=function(){return!1}})})};b.disableSelection=function(a){try{a.style.userSelect="none"}catch(f){}try{a.style.MozUserSelect="none"}catch(f){}try{a.style.webkitUserSelect="none"}catch(f){}try{a.style.khtmlUserSelect="none"}catch(f){}try{a.style.oUserSelect="none"}catch(f){}try{a.style.msUserSelect=
"none"}catch(f){}try{a.msUserSelect="none"}catch(f){}a.onselectstart=function(){return!1}};b.counter=function(a){return 9>a?"0"+(a+1):a+1};b.isNumber=function(a){return!isNaN(parseFloat(a))&&isFinite(a)};b.getRandomInt=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};b.formatCurrentTime=function(a){a=Math.round(a);minutes=Math.floor(a/60);minutes=10<=minutes?minutes:""+minutes;a=Math.floor(a%60);return minutes+":"+(10<=a?a:"0"+a)};b.formatDuration=function(a){a=Math.round(a);minutes=Math.floor(a/
60);minutes=10<=minutes?minutes:""+minutes;a=Math.floor(a%60);return minutes+":"+(10<=a?a:"0"+a)};b.hmsToSecondsOnly=function(a){a=a.split(":");for(var b=0,d=1;0<a.length;)b+=d*parseInt(a.pop()),d*=60;return b};b.checkBoolean=function(a){if("string"===typeof a)switch(a.toLowerCase()){case "true":case "yes":case "1":return!0;case "false":case "no":case "0":case null:return!1;default:return!!a}else if("boolean"===typeof a)return!!a};c.AWPUtils=b})(window);
(function(c,b){c.AWPTooltip=function(a){b("body");b(document);var f=b(c),d=a.parent,z=!1,l;this.setData=function(){l=0<d.find(".awp-tooltip").length?d.find(".awp-tooltip"):b('<div class="awp-tooltip"><p class="awp-tooltip-inner"></p></div>').appendTo(d).hide()};this.show=function(){};this.hide=function(){l.hide()};this.seekbar=function(a,b,c,v){if(z)return!1;l.addClass("awp-tooltip-num").find("p").text(AWPUtils.formatCurrentTime(c)+" / "+AWPUtils.formatDuration(v));c=d.offset().left;v=d.offset().top;
b.offset();var q=b.offset().top;b.outerWidth();var C=b.outerHeight(),u=l.outerWidth(),J=l.outerHeight(),w=f.width();f.height();var y=f.scrollLeft();f.scrollTop();a=a.pageX;var h=a-c;if(b.hasClass("awp-tooltip-top")){var K=h-u/2;var N=q-v-J}else b.hasClass("awp-tooltip-bottom")&&(K=h-u/2,N=q-v+C+15);K+u+c-y>w&&(K=a-c-u);0>K+c-y&&(K=a-c);K+u+c-y>w&&(K=w-u-c+y);l.css({left:parseInt(K,10)+"px",top:parseInt(N,10)+"px"}).show()};this.circle=function(a,b,c,v){if(z)return!1;l.addClass("awp-tooltip-num").find("p").text(AWPUtils.formatCurrentTime(c)+
" / "+AWPUtils.formatDuration(v));a=d.offset().left;c=d.offset().top;v=b.offset().left;var q=b.offset().top,f=b.outerWidth();b.outerHeight();var C=l.outerWidth(),u=l.outerHeight();if(b.hasClass("awp-tooltip-top")){var w=v-a+f/2-C/2;var y=q-c-u-10}l.css({left:parseInt(w,10)+"px",top:parseInt(y,10)+"px"}).show()};this.volume=function(a,b,c){if(z)return!1;l.addClass("awp-tooltip-num").find("p").text(c+" %");c=d.offset().left;var v=d.offset().top,f=b.offset().left,q=b.offset().top,C=b.outerWidth(),u=
b.outerHeight(),w=l.outerWidth(),y=l.outerHeight(),h=a.pageX-c;a=a.pageY-v;if(b.hasClass("awp-tooltip-top"))if(b.hasClass("awp-vertical")){var K=f-c+C/2-w/2;var N=a-y-10}else K=h-w/2,N=q-v-y;else b.hasClass("awp-tooltip-bottom")?b.hasClass("awp-vertical")?(K=f-c+C/2-w/2,N=a+y+10):(K=h-w/2,N=q-v+u+10):b.hasClass("awp-tooltip-left")&&b.hasClass("awp-vertical")&&(K=f-c-w-5,N=a-y/2);l.css({left:parseInt(K,10)+"px",top:parseInt(N,10)+"px"}).show()};this.controls=function(a,b){if(z)return!1;l.removeClass("awp-tooltip-num").find("p").text(b);
var c=d.offset().left,f=d.offset().top,q=a.offset().left,m=a.offset().top,u=a.outerWidth(),J=a.outerHeight(),w=l.outerWidth(),y=l.outerHeight();a.hasClass("awp-tooltip-top")?(c=q-c+u/2-w/2,f=m-f-y):a.hasClass("awp-tooltip-top-right")?(c=q-c,f=m-f-y):a.hasClass("awp-tooltip-top-left")?(c=q-c+u-w,f=m-f-y):a.hasClass("awp-tooltip-right")?(c=q-c+u+10,f=m-f+J/2-y/2):a.hasClass("awp-tooltip-bottom")?(c=q-c+u/2-w/2,f=m-f+J+10):a.hasClass("awp-tooltip-bottom-left")?(c=q-c+u-w,f=m-f+J+10):a.hasClass("awp-tooltip-left")?
(c=q-c-10-w,f=m-f+J/2-y/2):(c=q-c+u/2-w/2,f=m-f-y);l.css({left:parseInt(c,10)+"px",top:parseInt(f,10)+"px"}).show()};this.setValue=function(a){l.find("p").text(a)};this.setState=function(a){z=a};this.setData()}})(window,jQuery);
(function(c,b){c.AWPTouchManager=function(a){function f(a){m||b(u).trigger("AWPTouchManager.MOUSE_MOVE",{elem:b(a.currentTarget),e:a})}function d(a){m||(b(a.currentTarget).off("mousemove",f).off("mouseleave",d),C.off("mouseleave",z),b(u).trigger("AWPTouchManager.MOUSE_LEAVE",{elem:b(a.currentTarget),e:a}))}function z(a){b(a.currentTarget).off("mousemove",f).off("mouseleave",d);C.off("mouseleave",z);b(u).trigger("AWPTouchManager.MOUSE_LEAVE",{elem:b(a.currentTarget),e:a})}function l(a){y&&(h=[a.pageX,
a.pageY]);if(!m){var c;if("touchstart"==a.type)if((c=a.originalEvent.touches)&&0<c.length)c=c[0];else return!1;else c=a.originalEvent,a.preventDefault();m=!0;C.on(J,function(a){a:if(!y||a.pageX!==h[0]||a.pageY!==h[1]){if("touchmove"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;else break a;if(1<c.length)break a;c=c[0]}else c=a.originalEvent;
a.preventDefault();b(u).trigger("AWPTouchManager.DRAG_MOVE",{elem:D,point:c,e:a})}}).on(w,function(a){q(a)});D.on(w,function(a){q(a)});b(u).trigger("AWPTouchManager.DRAG_START",{elem:D,point:c,e:a})}return!1}function q(a){if(m){m=!1;C.off(J).off(w);D.off(w);if("touchend"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;else return!1;if(1<c.length)return!1;
c=c[0]}else c=a.originalEvent;a.preventDefault();v||C.off("mouseleave",z);b(u).trigger("AWPTouchManager.DRAG_RELEASE",{name:"DRAG_RELEASE",elem:D,point:c,e:a})}return!1}var u=this;b("body");var C=b(document);b(c);var v=AWPUtils.isMobile(),D,m=!1,I,J,w,y=AWPUtils.isChrome(),h=[];this.setData=function(){"ontouchstart"in c?(I="touchstart.ap mousedown.ap",J="touchmove.ap mousemove.ap",w="touchend.ap mouseup.ap"):c.PointerEvent?(I="pointerdown.ap",J="pointermove.ap",w="pointerup.ap"):(I="mousedown.ap",
J="mousemove.ap",w="mouseup.ap");var h,N=a.length;for(h=0;h<N;h++)a[h].on(I,function(a){a.preventDefault();if(m)return!1;D=b(this);l(a);return!1});if(!v)for(h=0;h<N;h++)a[h].on("mouseenter",function(a){if(m)return!1;D=b(this).on("mouseleave",d);if(D.data("apmove"))D.on("mousemove",f);C.on("mouseleave",z);b(u).trigger("AWPTouchManager.MOUSE_ENTER",{elem:D,e:a})})};this.isDrag=function(){return m};this.setData()}})(window,jQuery);
(function(c,b){c.AWPDownloadManager=function(a){function f(a,c,f){b.ajax({type:"POST",url:q+"includes/mail.php",data:"mail="+a+"&title="+c+"&path="+f}).done(function(a){v=!1}).fail(function(a,b,c){console.log("Send email error: "+a.responseText);d();v=!1});C.css({marginTop:parseInt(-C.height()/2,10)+"px",display:"block"}).stop().animate({opacity:1},{duration:500});I&&clearTimeout(I);I=setTimeout(d,2E3)}function d(){I&&clearTimeout(I);C.stop().animate({opacity:0},{duration:500,complete:function(){C.css("display",
"none")}})}var z=AWPUtils.isMobile();b("body");b(document);var l=a.parent,q=a.settings.sourcePath,u,C,v,D,m,I;this.setData=function(){u=0<l.find("iframe.awp-dl-iframe").length?l.find("iframe.awp-dl-iframe"):b('<iframe class="awp-dl-iframe"/>').css({position:"absolute",left:"-10000px",display:"none"}).appendTo(l);z&&(C=l.find(".awp-download-confirm"))};this.download=function(a,b){if(v)return!1;if("file:"==c.location.protocol)return console.log("Downloading files locally is not possible! This requires online server connection."),
!1;var d=a;var h=b;d.indexOf("\\")&&(d=d.replace(/\\/g,"/"));d.match(/^http([s]?):\/\/.*/)||(d=AWPUtils.qualifyURL(d));z||(h=h.replace(/[^A-Z0-9\-_\.]+/ig,"_"));50<h.length&&(h=h.substr(0,50)+"...");z||/\.(mp3)$/i.test(h)||(h+=".mp3");if(z){v=!0;if(!D){for(var l=prompt("Please enter your email address where download link will be sent:");(!AWPUtils.validateEmail(l)||AWPUtils.isEmpty(l))&&null!=l;)l=prompt("Please enter a valid email address:");(m=l)&&(D=!0)}m?f(m,h,d):v=!1}else u.attr("src",q+"includes/dl.php?path="+
d+"&title="+h)};this.setData()}})(window,jQuery);
(function(c,b){c.AWPShareManager=function(a){AWPUtils.isMobile();var b=a.settings.facebookAppId,d="https:"==c.location.protocol?"https:":"http:";this.setData=function(){if(AWPUtils.isEmpty(b))console.log("facebookAppId has not been set in settings!");else if(!c.FB&&b&&!document.body.querySelector("#fb-root")){var a=document.createElement("script");a.text="window.fbAsyncInit=function(){FB.init({appId:'"+b+"',status:true,xfbml:true})};(function(e,t,n){var r,i=e.getElementsByTagName(t)[0];if(e.getElementById(n)){return}r=e.createElement(t);r.id=n;r.src='"+d+
"//connect.facebook.net/en_US/all.js';i.parentNode.insertBefore(r,i)})(document,'script','facebook-jssdk')";var l=document.createElement("div");l.id="fb-root";document.body.appendChild(l);document.body.appendChild(a)}};this.share=function(a,b,f){var l=(c.screen.width-600)/2,z=(c.screen.height-300)/2,q=b.description||"",D=b.thumb?AWPUtils.qualifyURL(b.thumb):"";b=b.share;AWPUtils.relativePath(D)||(D=AWPUtils.qualifyURL(D));if("facebook"==a){var m=d+"//www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(b);
if(c.FB){c.FB&&FB.ui({method:"feed",name:document.title,link:b,picture:D,caption:f});return}}else"twitter"==a?m=d+"//twitter.com/share?url="+encodeURIComponent(b)+"&text="+encodeURIComponent(f):"googleplus"==a?m=d+"//plus.google.com/share?url="+encodeURIComponent(b):"tumblr"==a&&(m=d+"//www.tumblr.com/share/link?url="+encodeURIComponent(b)+"&amp;name="+encodeURIComponent(f)+"&amp;description="+encodeURIComponent(q));m&&c.open(m,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,width=600,height=300,left="+
l+",top="+z)};this.setData()}})(window,jQuery);
(function(c,b){c.AWPSoundLoader=function(a){function f(){D.length?(v=D.shift(),I=0,y=v.limit||500,d()):b(u).trigger("AWPSoundLoader.END_LOAD",[m])}function d(){if("file:"==c.location.protocol)alert("Using "+v.type+" locally is not possible! This requires online server connection!"),f();else{var a=v.type,d=v.path;"podcast"==a?(a=C+"?url="+encodeURIComponent(d),b.ajax({url:a,dataType:"json",cache:!1}).done(function(a){var c=AWPUtils.parseXML(a.contents),d,h,l,z=0;b(c).find("image").length&&b(c).find("image").attr("href")?
l=b(c).find("image").attr("href"):b(a.contents).find("itunes\\:image").length&&b(a.contents).find("itunes\\:image").attr("href")&&(l=b(a.contents).find("itunes\\:image").attr("href"));b(c).find("item").each(function(){if(z==y)return!1;d=b(this);h=b.extend(!0,{},v);h.type="audio";h.mp3=d.find("enclosure").attr("url");"undefined"===typeof h.download&&(h.download=h.mp3);!h.title&&d.find("title").length&&(h.title=d.find("title").text());!h.artist&&d.find("author").length&&(h.artist=d.find("author").text());
!h.description&&d.find("description").length&&(h.description=d.find("description").text());!h.duration&&d.find("duration").length&&(h.duration=d.find("duration").text());h.thumb||(d.find("image").length&&d.find("image").attr("href")?h.thumb=d.find("image").attr("href"):l&&(h.thumb=l));"undefined"===typeof h.share&&d.find("link").length&&(h.share=d.find("link").text());m.push(h);z++});f()}).fail(function(a,b,c){console.log(a,b,c);f()})):"soundcloud"==a&&(J?l(d):z(d))}}function z(a){if(AWPUtils.isEmpty(w))return alert("soundCloudAppId has not been set!"),
f(),!1;var b=document.createElement("script");b.src="https://connect.soundcloud.com/sdk.js";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);var h=setInterval(function(){c.SC&&(h&&clearInterval(h),SC.initialize({client_id:w}),J=!0,l(a))},100)}function l(a){SC.get(a,{limit:200,linked_partitioning:1},function(a,b){if(b)console.log("Error getSoundCloudPage: "+b),f();else{if("track"==a.kind)q(a);else if("playlist"==a.kind){var c,d=a.tracks.length;if(m.length+d>=y){d=y-m.length;
var h=!0}for(c=0;c<d;c++)q(a.tracks[c],!0)}else if(a.collection)for(d=a.collection.length,m.length+d>=y&&(d=y-m.length,h=!0),c=0;c<d;c++)q(a.collection[c],!0);a.next_href&&!h?l(a.next_href):f()}})}function q(a,b){if(a.streamable&&a.stream_url){var c=jQuery.extend(!0,{},v);c.deeplink&&"undefined"!==typeof b&&(c.deeplink+=(I+1).toString(),I++);c.type="audio";a.duration&&(c.duration=a.duration);c.mp3=a.stream_url+"?client_id="+w;"undefined"===typeof c.download&&a.downloadable&&a.download_url&&(c.download=
c.mp3.replace(/\/stream\\?/,"/download"));!c.title&&a.title&&(c.title=a.title);!c.description&&a.description&&(c.description=a.description);!c.thumb&&a.artwork_url&&(c.thumb=a.artwork_url,c.thumbQuality&&(c.thumb=c.thumb.replace("large.jpg",c.thumbQuality)));c.favoritings_count=parseInt(a.favoritings_count?a.favoritings_count:0,10);c.playback_count=parseInt(a.playback_count?a.playback_count:0,10);c.hotness=c.favoritings_count+c.playback_count;"undefined"===typeof c.share&&a.permalink_url&&(c.share=
a.permalink_url);m.push(c)}}var u=this,C=a.settings.sourcePath+"includes/ba-simple-proxy.php",v,D=[],m=[],I,J,w=a.settings.soundCloudAppId;b("<div/>");var y;this.setData=function(a){m=[];D=b.extend(!0,[],[a]);f()}}})(window,jQuery);
(function(c,b){c.AWPPlaylistManager=function(a){function c(){3>d.playlistItems?d.randomPlay=!1:d.randomArr=AWPUtils.randomiseArray(d.playlistItems)}var d=this;this.loopingOn=a.loopingOn;this.randomPlay=a.randomPlay;this.playlistItems;this.lastInOrder=!1;this.counter=-1;this.lastPlayedFromPlaylistClick;this.lastRandomCounter;this.randomPaused=!1;this.randomArr=[];this.playlistSelect=!1;this.setCounter=function(a,l){"undefined"===typeof l&&(l=!0);d.counter=l?d.counter+parseInt(a,10):parseInt(a,10);
if(isNaN(d.counter))alert("AWPPlaylistManager message: No active media, counter = "+d.counter);else if(d.lastInOrder=!1,d.loopingOn){if(d.randomPlay)if(d.counter>d.playlistItems-1){d.counter=d.randomArr[d.playlistItems-1];c();if(d.randomArr[0]==d.counter){var f=d.randomArr.splice(0,1);d.randomArr.push(f)}d.counter=0;b(d).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")}else 0>d.counter&&(d.counter=d.randomArr[0],c(),d.randomArr[d.playlistItems-1]==d.counter&&(f=d.randomArr.splice(d.playlistItems-
1,1),d.randomArr.unshift(f)),d.counter=d.playlistItems-1);else d.counter>d.playlistItems-1?(d.counter=0,b(d).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")):0>d.counter&&(d.counter=d.playlistItems-1);b(d).trigger("AWPPlaylistManager.COUNTER_READY")}else d.counter>d.playlistItems-1?(d.counter=d.playlistItems-1,d.lastInOrder=!0):0>d.counter&&(d.counter=0),d.lastInOrder?b(d).trigger("AWPPlaylistManager.PLAYLIST_END"):b(d).trigger("AWPPlaylistManager.COUNTER_READY")};this.getCounter=function(){return d.randomPlay?
d.playlistSelect?d.counter:d.randomArr[d.counter]:d.counter};this.advanceHandler=function(a){d.playlistSelect=!1;d.randomPaused?(d.randomPaused=!1,d.lastRandomCounter+a>d.playlistItems-1?(d.counter=d.playlistItems-1,b(d).trigger("AWPPlaylistManager.COUNTER_READY")):0>d.lastRandomCounter+a?(d.counter=0,b(d).trigger("AWPPlaylistManager.COUNTER_READY")):d.setCounter(d.lastRandomCounter+a,!1)):d.setCounter(a)};this.processPlaylistRequest=function(a){d.playlistSelect=!1;d.randomPlay&&(d.playlistSelect=
!0,d.lastPlayedFromPlaylistClick=a,d.randomPaused||(d.lastRandomCounter=d.counter,d.randomPaused=!0));this.setCounter(a,!1)};this.setPlaylistItems=function(a,b){"undefined"===typeof b&&(b=!0);b&&(d.counter=-1);d.playlistItems=a;d.randomPlay&&c()};this.reSetCounter=function(a){"undefined"===typeof a?d.counter=-1:(a=parseInt(a,10),d.playlistItems?(a>d.playlistItems-1?a=d.playlistItems-1:0>a&&(a=0),d.counter=a):d.counter=-1)};this.setRandom=function(a){d.randomPlay=a;d.randomPlay&&c();if(d.randomPlay){var b=
d.randomArr.length;for(a=0;a<b;a++)if(d.randomArr[a]==d.counter){if(0==a)break;a=d.randomArr.splice(a,1);d.randomArr.unshift(parseInt(a,10));break}d.counter=0}else d.randomPaused?(d.counter=d.lastPlayedFromPlaylistClick,d.randomPaused=!1):d.counter=d.randomArr[d.counter]};this.setLooping=function(a){d.loopingOn=a}}})(window,jQuery);
(function(c){c.fn.awp=function(b){function a(a){if(!k)return!1;0<A?(Qa=A,A=0):A=Qa;f();"undefined"!==typeof a&&"undefined"!==typeof Q&&void 0!=pa.attr("data-awptooltip")&&Q.controls(pa,0==A?"UnMute":"Mute")}function f(a){"undefined"!==typeof a&&(A=a);"undefined"!==typeof A&&(t.volume=A,"undefined"!==typeof e&&e.setVolume(A));qa&&(aa?jb.css("width",A*U+"px"):jb.css("height",A*U+"px"));0==A?qa&&pa.find("i").removeClass("fa-volume-up fa-volume-down").addClass("fa-volume-off"):qa&&pa.find("i").removeClass("fa-volume-off fa-volume-down").addClass("fa-volume-up");
awpVolumeChange(x,E,A)}function d(a){a.preventDefault();if(!k)return!1;var g=c(a.currentTarget),b=g.attr("data-id");if(b==n.getCounter())return!1;Ra=!0;n.processPlaylistRequest(b);awpPlaylistItemClick(x,E,g,b,a)}function z(a){a.preventDefault();if(!k)return!1;a=c(a.currentTarget);var g=a.attr("data-id");if(g==n.getCounter())return!1;a.removeClass("awp-playlist-non-selected").addClass("awp-playlist-selected");awpPlaylistItemRollover(x,E,a,g)}function l(a){a.preventDefault();if(!k)return!1;a=c(a.currentTarget);
var g=a.attr("data-id");if(g==n.getCounter())return!1;a.removeClass("awp-playlist-selected").addClass("awp-playlist-non-selected");awpPlaylistItemRollout(x,E,a,g)}function q(g){if(!k)return!1;g=c(g.currentTarget);g.hasClass("awp-prev-toggle")?x.previousMedia():g.hasClass("awp-playback-toggle")?x.togglePlayback():g.hasClass("awp-next-toggle")?x.nextMedia():g.hasClass("awp-loop-toggle")?(R=!R,n.setLooping(R),R?ja.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):ja.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")):
g.hasClass("awp-player-volume")?g.hasClass("awp-toggle-mute")&&a():g.hasClass("awp-random-toggle")?(S=!S,n.setRandom(S),S?ka.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):ka.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")):g.hasClass("awp-sort-alpha")?(x.sort("title",Aa),(Aa=!Aa)?g.find("i").removeClass("fa-sort-alpha-desc").addClass("fa-sort-alpha-asc"):g.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc")):g.hasClass("awp-share-item")&&
void 0!=g.attr("data-type")&&"undefined"!==typeof kb&&p.share&&!AWPUtils.isEmpty(p.share)&&kb.share(g.attr("data-type").toLowerCase(),p,ra(n.getCounter()))}function u(a){if(!k)return!1;a.preventDefault();if("undefined"!==typeof Sa&&Sa.isDrag())return!1;a=c(a.currentTarget);var g=a.find("i");g.hasClass("awp-icon-color")&&g.removeClass("awp-icon-color").addClass("awp-icon-rollover-color");"undefined"!==typeof Q&&void 0!=a.attr("data-awptooltip")&&(g=a.hasClass("awp-player-volume")?0==A?"UnMute":"Mute":
a.attr("data-awptooltip"),Q.controls(a,g))}function C(a){if(!k)return!1;a.preventDefault();a=c(a.currentTarget);var g=a.find("i");a.hasClass("awp-random-toggle")&&S||a.hasClass("awp-loop-toggle")&&R||g.hasClass("awp-icon-rollover-color")&&g.removeClass("awp-icon-rollover-color").addClass("awp-icon-color");"undefined"!==typeof Q&&Q.hide()}function v(){if(-1!=n.getCounter()){var a=Z,c=F.children("div.awp-playlist-item[data-id="+a+"]"),b=c.find(".awp-playlist-non-selected, .awp-playlist-selected");c.length&&
(a=c.attr("data-id"),b.removeClass("awp-playlist-selected").addClass("awp-playlist-non-selected"),"undefined"!==typeof awpPlaylistItemEnabled&&awpPlaylistItemEnabled(x,E,c,a))}}function D(a){Ba=c.ajax({url:sa+"peaks/peaks.php",type:"post",data:[{name:"action",value:"awp_read_peaks"},{name:"id",value:a},{name:"path",value:p.peakdir||null}],dataType:"json"}).done(function(a){a.length?(e.backend.peaks=a,Ca=!0,Ta?e.drawBuffer():e.load(p.mp3,e.backend.peaks)):(e.backend.supportsWebAudio()?(Ua=!0,p.remote&&
(ta.css("opacity",1).html("Loading waveform..."),e.setSkipArrayBuffer(!0),J())):p.peakImage&&(ea=!0,Va.empty().append('<img src="'+p.peakImage.load+'" alt="load"/>'),la.empty().append('<img src="'+p.peakImage.progress+'" alt="progress"/>'),T.css("display","block"),la.width(T.width()),T.removeClass("awp-hidden").addClass("awp-visible"),Da()),console.log("currMediaData.mp3 ",p.mp3),e.load(p.mp3))}).fail(function(a,g,c){console.log(a,g,c)})}function m(a,b){c.ajax({url:sa+"peaks/peaks.php",type:"post",
data:[{name:"action",value:"awp_write_peaks"},{name:"peaks",value:a},{name:"id",value:b},{name:"path",value:p.peakdir||null}],dataType:"json"}).done(function(a){}).fail(function(a,g,c){console.log(a.responseText)})}function I(){p.peakData?(e.backend.peaks=p.peakData,Ca=!0,e.drawBuffer(),Ta?e.drawBuffer():e.load(p.mp3,e.backend.peaks)):p.peakImage?(ea=!0,Va.empty().append('<img src="'+p.peakImage.load+'" alt="load"/>'),la.empty().append('<img src="'+p.peakImage.progress+'" alt="progress"/>'),T.css("display",
"block"),la.width(T.width()),T.removeClass("awp-hidden").addClass("awp-visible"),Da(),e.setSkipArrayBuffer(!0),e.load(p.mp3)):D(p.peakName||p.title)}function J(){Ea=c.ajax({url:sa+"peaks/remote_dl.php",type:"post",data:[{name:"id",value:p.mp3},{name:"title",value:p.title},{name:"path",value:p.peakdir||null}],dataType:"json"}).done(function(a){console.log(a);e._getArrayBuffer(a)}).fail(function(a,c,b){console.log(a,c,b)})}function w(a){V=!0;lb();O&&Wa();var g=Fb.find("#"+a);if(0==g.length)return alert('Failed to select playlist! Check activePlaylist option in settings. Make sure that element: "'+
a+'" exist in awp-playlist-list!'),Xa.css("display","none"),V=!1;"undefined"!==typeof awpPlaylistStartLoad&&awpPlaylistStartLoad(x,E);var b,d;g.find(".awp-playlist-item").each(function(){d=c(this);b=y(d);W.push(b)});B=W.length;h()}function y(a){var c={};c.origclasses=a.attr("class");c.type=a.attr("data-type");a.is(":empty")||(c.content=a.html());"audio"==c.type?c.mp3=a.attr("data-mp3"):void 0==a.attr("data-path")||AWPUtils.isEmpty(a.attr("data-path"))||(c.path=c.id=a.attr("data-path"));void 0==a.attr("data-peak-load")||
AWPUtils.isEmpty(a.attr("data-peak-load"))||void 0==a.attr("data-peak-progress")||AWPUtils.isEmpty(a.attr("data-peak-progress"))||(c.peakImage={load:a.attr("data-peak-load"),progress:a.attr("data-peak-progress")});void 0!=a.attr("data-peak-array")&&(c.peakData=a.attr("data-peak-array").split(","));void 0!=a.attr("data-peak-name")&&(c.peakName=a.attr("data-peak-name"));AWPUtils.isEmpty(a.html())||(c.content=a.html());void 0!=a.attr("data-limit")&&!AWPUtils.isEmpty(a.attr("data-limit"))&&AWPUtils.isNumber(a.attr("data-limit"))&&
0!=Math.abs(parseInt(a.attr("data-limit"),10))&&(c.limit=Math.abs(parseInt(a.attr("data-limit"),10)));void 0==a.attr("data-thumb")||AWPUtils.isEmpty(a.attr("data-thumb"))?void 0==a.attr("data-thumb-default")||AWPUtils.isEmpty(a.attr("data-thumb-default"))||(c.thumbDefault=a.attr("data-thumb-default")):c.thumb=a.attr("data-thumb");void 0==a.attr("data-thumb-quality")||AWPUtils.isEmpty(a.attr("data-thumb-quality"))||(c.thumbQuality=a.attr("data-thumb-quality"));void 0==a.attr("data-title")||AWPUtils.isEmpty(a.attr("data-title"))||
(c.title=a.attr("data-title"));void 0==a.attr("data-artist")||AWPUtils.isEmpty(a.attr("data-artist"))||(c.artist=a.attr("data-artist"));void 0==a.attr("data-description")||AWPUtils.isEmpty(a.attr("data-description"))||(c.description=a.attr("data-description"));void 0!=a.attr("data-download")&&(c.download=a.attr("data-download"));void 0!=a.attr("data-id3")&&(c.id3=!0);void 0==a.attr("data-dir-url")||AWPUtils.isEmpty(a.attr("data-dir-url"))||(c.dirurl=a.attr("data-dir-url"));void 0==a.attr("data-peak-dir")||
AWPUtils.isEmpty(a.attr("data-peak-dir"))||(c.peakdir=a.attr("data-peak-dir"));void 0!=a.attr("data-start")&&!AWPUtils.isEmpty(a.attr("data-start"))&&AWPUtils.isNumber(a.attr("data-start"))&&0!=a.attr("data-start")&&(c.start=Math.abs(a.attr("data-start")));void 0!=a.attr("data-end")&&!AWPUtils.isEmpty(a.attr("data-end"))&&AWPUtils.isNumber(a.attr("data-end"))&&0!=a.attr("data-end")&&(c.end=Math.abs(a.attr("data-end")));void 0!=a.attr("data-duration")&&!AWPUtils.isEmpty(a.attr("data-duration"))&&AWPUtils.isNumber(a.attr("data-duration"))&&
0!=Math.abs(a.attr("data-duration"))&&(c.duration=Math.abs(a.attr("data-duration")));void 0!=a.attr("data-playback-rate")&&(c.playbackRate=1,!AWPUtils.isEmpty(a.attr("data-playback-rate"))&&AWPUtils.isNumber(a.attr("data-playback-rate"))&&0!=a.attr("data-playback-rate")&&(c.playbackRate=Math.abs(a.attr("data-playback-rate"))));void 0==a.attr("data-link")||AWPUtils.isEmpty(a.attr("data-link"))||(c.link=a.attr("data-link"),c.target="_blank",void 0==a.attr("data-target")||AWPUtils.isEmpty(a.attr("data-target"))||
(c.target=a.attr("data-target")));void 0!=a.attr("data-share")&&(c.share=a.attr("data-share"));void 0!=a.attr("data-remote")&&(c.remote=!0);return c}function h(){ba++;if(ba>B-1)Db();else{var a=W[ba],b=W[ba].type;/^audio$/.test(b)?(X.push(a),h()):-1<c.inArray(b,Gb)?mb.setData(a):/^folder$/.test(b)?K(b):/^gdrive-folder$/.test(b)?N(b):(console.log("Wrong data-type in playlist! Type = "+b),h())}}function K(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),
h(),!1;var b=W[ba],g=b.path.replace(/\/\//g,"/");a=sa+"includes/folder_parser.php";g={dir:g,limit:b.limit||1E4};b.id3&&(nb=ua=X.length-1);c.ajax({type:"GET",url:a,data:g,dataType:"json"}).done(function(a){AWPUtils.keysrt(a,"filename");var g,d=a.length;for(g=0;g<d;g++){var Y=a[g];if(/.mp3/.test(Y.basename)){var H=c.extend(!0,{},b);H.type="audio";var e=H.dirurl?H.dirurl+Y.basename:Y.fullpath;H.mp3=e;"undefined"!==typeof H.download&&AWPUtils.isEmpty(H.download)&&(H.download=e);"undefined"!==typeof H.share&&
AWPUtils.isEmpty(H.share)&&(H.share=e);H.title||(H.title=Y.filename);X.push(H);ua++}}b.id3?Oa():h()}).fail(function(a,c,b){console.log("Error processing folder: "+a.responseText);h()})}function N(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),h(),!1;if(AWPUtils.isEmpty(t.gDriveAppId))return console.log("gDriveAppId has not been set in settings!"),h(),!1;var b=W[ba];c.ajax({url:"https://www.googleapis.com/drive/v3/files?q='"+
b.path+"'+in+parents&key="+t.gDriveAppId,dataType:"jsonp"}).done(function(a){var g,d=a.files.length,H=[],Y=[];for(g=0;g<d;g++){var e=a.files[g];/.mp3|mpeg|mpeg3/.test(e.mimeType)?(Y.push(e),AWPUtils.keysrt(Y,"name")):/.jpg|jpeg|png/.test(e.mimeType)&&(H.push(e),AWPUtils.keysrt(H,"name"))}d=Y.length;for(g=0;g<d;g++){e=Y[g];a=c.extend(!0,{},b);a.type="audio";var f="https://drive.google.com/uc?export=view&id="+e.id;a.mp3=f;console.log(f);"undefined"!==typeof a.download&&AWPUtils.isEmpty(a.download)&&
(a.download="https://drive.google.com/uc?export=download&id="+e.id);"undefined"!==typeof a.share&&AWPUtils.isEmpty(a.share)&&(a.share="https://drive.google.com/open?id="+e.id);H.length&&!a.thumb&&H[g]&&(a.thumb="https://drive.google.com/uc?export=view&id="+H[g].id);a.title||(a.title=e.name.substr(0,e.name.lastIndexOf(".")));X.push(a)}h()}).fail(function(a,c,b){console.log("Error processing gdrive folder: "+a.responseText);h()})}function Oa(){var a=X[ua];jsmediatags.read(a.mp3,{onSuccess:function(c){var b=
c.tags;c=b.picture;b.artist&&(a.artist=b.artist);b.title&&(a.title=b.title);b.album&&(a.album=b.album);if(c){b="";var g,d=c.data.length;for(g=0;g<d;g++)b+=String.fromCharCode(c.data[g]);a.thumb="data:"+c.format+";base64,"+window.btoa(b)}ua--;ua>nb?Oa():h()},onError:function(a){console.log("ID3 error: ",a.type,a.info);Oa()}})}function Db(){var a,b=ca?M:G.length,e=X.length,f=0;for(a=0;a<e;a++){var h=a+b;ca&&f++;var k=X[a];var p=k.type;if(fa){k.origclasses||(k.origclasses="awp-playlist-item");var m=
c('<div class="'+k.origclasses+'"/>').attr({"data-type":p});delete k.origclasses;if(ca){t?t.after(m):ma?m.appendTo(F):F.children("div").eq(M).before(m);var t=m}else m.appendTo(F);var q=c('<a class="awp-playlist-non-selected" href="#"/>').on("click",d).appendTo(m);if(!va)q.on("mouseenter",z).on("mouseleave",l);if(-1!=c.inArray("thumb",ob)){var r=k.thumb||k.thumbDefault;if(r){var u=new Image;u.className="awp-hidden";u.onload=function(){this.className="awp-visible"};u.src=r;c('<span class="awp-playlist-thumb"></span>').append(u).appendTo(q)}}-1!=
c.inArray("title",ob)&&c('<span class="awp-playlist-title"></span>').appendTo(q);k.link&&(r=c('<a class="awp-link" href="'+k.link+'" target="'+(k.target||"_blank")+'"><i class="fa fa-external-link"></i></a>'),q.after(r));k.download&&(r=pb?c('<a class="awp-download" href="'+k.download+'" download><i class="fa fa-download"></i></a>'):c('<a class="awp-download" href="#" title="download"><i class="fa fa-download"></i></a>'),q.after(r));k.content&&(m.after(k.content),delete k.content)}G.splice(h,0,{id:h,
type:p,data:k})}fa&&Eb();O=F;Pa();console.log("playlistDataArr = ",G);ca||Ya?(h=n.getCounter(),n.setPlaylistItems(B,!1),M<=h&&(ma||n.reSetCounter(h+f)),wa?(wa=!1,xa&&!va&&(ha=!0),n.setCounter(M,!1)):xa&&n.setCounter(M,!1),-1!=n.getCounter()&&(Z=n.getCounter())):n.setPlaylistItems(B);qb();0==B&&"undefined"!==typeof awpPlaylistEmpty&&awpPlaylistEmpty(x,E,F);Fa=!0;"undefined"!==typeof awpPlaylistEndLoad&&awpPlaylistEndLoad(x,E,F)}function Pa(){B=G.length;if(fa){var a=0,b,d,e,f;Ga=[];F.find("div.awp-playlist-item").each(function(){d=
c(this).attr("data-id",a);e=d.find(".awp-playlist-non-selected, .awp-playlist-selected").attr("data-id",a);f=e.find(".awp-playlist-title");f.length&&(b=ra(a),Za&&(Ga.push(b),G[a].data.title_full=b),rb?f.html(AWPUtils.counter(a)+sb+b):f.html(b));G[a].id=a;a++});Ha&&Ia&&0<B&&"h"==Ja.charAt(0)&&ia.mCustomScrollbar("update")}}function Eb(){F.children(".awp-playlist-item").each(function(){if(!pb)c(this).find("a[class=awp-download]").off("click").on("click",function(a){a.preventDefault();"undefined"!==
typeof tb&&(a=c(this).parent().attr("data-id"),a=G[a].data,"undefined"===typeof a.download||AWPUtils.isEmpty(a.download)||tb.download(a.download,a.title||"media"))})})}function ib(a){var c="h"==Ja.charAt(0)?"x":"y";ia.mCustomScrollbar({axis:c,theme:a||t.playlistScrollTheme,scrollInertia:0,mouseWheel:{normalizeDelta:!0,deltaFactor:50,preventDefault:!0},keyboard:{enable:!1},advanced:{autoExpandHorizontalScroll:!0}});Ia=!0}function qb(){ca=Ya=!1;Xa.css("display","none");V=!1;k||(k=!0,fa&&!Ia&&Ha&&ib(),
f(A),awpSetupDone(x,E));if(!$a&&!ca&&0<B){var a=t.activeItem;a>B-1&&(a=B-1);-1<a&&n.setCounter(a,!1);$a=!0}}function ub(){"undefined"!==typeof awpMediaEnd&&awpMediaEnd(x,E,n.getCounter());if(Hb)x.nextMedia();else{var a=p.start||0;"loop"==ab?e.play(a):"rewind"==ab?(e.pause(),e.seekTo(a/e.getDuration())):"stop"==ab&&e.pause()}}function vb(){k&&"undefined"!==typeof L&&(fa&&-1!=Z&&v(),Ka(),n.reSetCounter())}function Ka(){Ea&&(Ea.abort(),Ea=null);Ba&&(Ba.abort(),Ba=null);"undefined"!==typeof e&&(e.empty(),
e.setSkipArrayBuffer(!1));ta.css("opacity",0);La.removeClass("awp-visible").addClass("awp-hidden");ea=!1;Va.empty();la.empty();T.css("display","none").removeClass("awp-visible").addClass("awp-hidden");ya.removeClass("awp-visible").addClass("awp-hidden");za.removeClass("awp-visible").addClass("awp-hidden");wb&&(ya.html("0:00"),za.html("0:00"));Ib.empty();xb();L=null;xa=Ma=P=!1;awpCleanMedia(x,E)}function Wa(){L&&Ka();fa&&O.find(".awp-playlist-item").remove();na=O=null;Fa=wa=ca=!1;Z=-1;$a=!1;B=0;ba=
-1;G=[];X=[];W=[];n.reSetCounter();Za&&yb.val(bb);Jb&&(Aa=!1,cb.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc"));awpDestroyPlaylist(x,E,F)}function Da(){ya.removeClass("awp-hidden").addClass("awp-visible");za.removeClass("awp-hidden").addClass("awp-visible")}function xb(){db.find("i").removeClass("fa-pause").addClass("fa-play")}function lb(){Xa.css("display","block")}function eb(a){if("string"===typeof a)var c=a;else"number"===typeof a&&(c=ra(a),rb&&(c=AWPUtils.counter(a)+
sb+c));Kb.html(c)}function ra(a){a=G[a].data;var c="";"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"!==typeof a.artist||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(c=a.artist):c=a.title:c=a.artist+zb+a.title;return c}var t=c.extend({},{instanceName:"",sourcePath:"",playlistList:"",activePlaylist:"",activeItem:0,volume:.5,
autoPlay:!1,randomPlay:!1,loopingOn:!0,autoAdvanceToNextMedia:!0,mediaEndAction:"loop",soundCloudAppId:"",usePlaylistScroll:!1,playlistScrollOrientation:"vertical",playlistScrollTheme:"light",useKeyboardNavigationForPlayback:!1,facebookAppId:"",useNumbersInPlaylist:!1,numberTitleSeparator:".  ",artistTitleSeparator:" - ",playlistItemContent:"title"},b),r=c(this).show(),Fb=c(t.playlistList).hide(),Lb=r.find(".awp-playlist-holder"),ia=r.find(".awp-playlist-inner"),F=r.find(".awp-playlist-content"),
fb=r.find(".awp-playlist-filter-msg"),cb=r.find(".awp-sort-alpha"),Xa=r.find(".awp-preloader");r.find(".awp-player-holder");var Ib=r.find(".awp-player-thumb"),ya=r.find(".awp-media-time-current"),za=r.find(".awp-media-time-total"),Kb=r.find(".awp-media-title");r.find(".awp-player-controls");var db=r.find(".awp-playback-toggle"),ja=r.find(".awp-loop-toggle"),pa=r.find(".awp-player-volume"),ka=r.find(".awp-random-toggle");r.find(".awp-volume-wrapper");var oa=r.find(".awp-volume-seekbar"),da=r.find(".awp-volume-bg"),
jb=r.find(".awp-volume-level"),La=r.find(".awp-waveform"),ta=r.find(".awp-waveform-preloader"),T=r.find(".awp-waveform-img"),Va=r.find(".awp-waveform-img-load"),Ab=r.find(".awp-waveform-img-progress-wrap"),la=r.find(".awp-waveform-img-progress"),va=AWPUtils.isMobile();AWPUtils.canPlayMp3();AWPUtils.canPlayWav();var sa=t.sourcePath,E=AWPUtils.filterAllowedChars(t.instanceName),na=t.activePlaylist,ha=t.autoPlay,Ta=t.drawWaveWithoutLoad,R=t.loopingOn,S=t.randomPlay,rb=t.useNumbersInPlaylist,sb=t.numberTitleSeparator,
zb=t.artistTitleSeparator,A=t.volume,Ha=t.usePlaylistScroll,Ja=t.playlistScrollOrientation.toLowerCase(),Mb=t.useKeyboardNavigationForPlayback,Hb=t.autoAdvanceToNextMedia,ab=t.mediaEndAction,ob=t.playlistItemContent.split(","),fa=Lb.length,Za=r.find(".awp-search-filter").length,Jb=cb.length,wb=ya.length||za.length,qa=oa.length,k=!1,V=!1,x=this;c("body");var Nb=c(window),Ob=c(document),Bb=AWPUtils.isIE(),gb,pb=AWPUtils.hasDownloadSupport(),Ua,ea,Ca,Ea,Ba,ma,M,ca,xa,wa,Ya,ba=-1,G=[],X=[],W=[],B=0,$a,
Fa=!1,O=null,Z=-1,Ma=!1,L,P=!1,p,Ra,Ia,Aa=!1,Ga=[],ua,nb,Gb=["podcast","soundcloud","soundcloud_query"];"undefined"===typeof window.awp_mediaArr&&(window.awp_mediaArr=[]);awp_mediaArr.push({inst:x,id:E});va&&(ha=!1);if(Bb&&12>Bb)T.on("click",function(a){if(ea){var b=c(a.currentTarget);a=Math.min(Math.max((a.pageX-b.offset().left)/b.width(),0),1);e.seekTo(a)}});R&&ja.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color");S&&ka.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color");
if(Za)var yb=r.find(".awp-search-filter").on("focus",function(a){c(this).val()==bb&&c(this).val("")}).on("blur",function(){AWPUtils.isEmpty(c(this).val())&&c(this).val(bb)}).on("keyup.apfilter",function(){if(0==Ga.length)return!1;var a=G.length,b=c(this).val();b=Ga.filter(/./.test.bind(new RegExp(b,"i")));var d,e=0;for(d=0;d<a;d++){var f=ra(d);-1<c.inArray(f,b)?F.children("div.awp-playlist-item").eq(d).show():(F.children("div.awp-playlist-item").eq(d).hide(),e++)}0<a&&fb.length&&(e==a?fb.show():fb.hide());
Ha&&0<B&&"h"==Ja.charAt(0)&&ia.mCustomScrollbar("update");"undefined"!==typeof awpFilterChange&&awpFilterChange(x,E,F)}),bb=yb.val();var Q=new AWPTooltip({settings:t,parent:r}),tb=new AWPDownloadManager({settings:t,parent:r}),kb=new AWPShareManager({settings:t}),n=new AWPPlaylistManager({randomPlay:S,loopingOn:R});c(n).on("AWPPlaylistManager.COUNTER_READY",function(){L&&Ka();if(fa){-1!=Z&&v();var a=n.getCounter(),c=F.children("div.awp-playlist-item[data-id="+a+"]"),b=c.find(".awp-playlist-non-selected, .awp-playlist-selected");
c.length&&(Z=a,b.removeClass("awp-playlist-non-selected").addClass("awp-playlist-selected"),Ha&&0<B&&(Ra||("h"==Ja.charAt(0)?ia.mCustomScrollbar("scrollTo",parseInt(c.position().left),{scrollInertia:500}):ia.mCustomScrollbar("scrollTo",parseInt(c.position().top),{scrollInertia:500})),Ra=!1),"undefined"!==typeof awpPlaylistItemDisabled&&awpPlaylistItemDisabled(x,E,c,a))}a=n.getCounter();p=G[a].data;L=p.type;eb(a);I();"undefined"!==typeof awpItemTriggered&&awpItemTriggered(x,E,a)}).on("AWPPlaylistManager.PLAYLIST_END AWPPlaylistManager.PLAYLIST_END_ALERT",
function(){"undefined"!==typeof awpPlaylistEnd&&awpPlaylistEnd(x,E)});var mb=new AWPSoundLoader({settings:t,sourcePath:sa});c(mb).on("AWPSoundLoader.END_LOAD",function(a,c){var b,d=c.length;for(b=0;b<d;b++){var g=c[b];X.push(g)}h()});var hb=[];qa&&(oa.data("apmove",!0),hb.push(oa));if(hb.length){var Sa=new AWPTouchManager(hb);c(Sa).on("AWPTouchManager.DRAG_START",function(a,c){}).on("AWPTouchManager.DRAG_MOVE AWPTouchManager.DRAG_RELEASE",function(a,c){if(!k)return!1;var b=c.elem,d=c.point.pageX,
g=c.point.pageY;if(b.hasClass("awp-volume-seekbar")){var e=aa?d:g;aa?A=Math.max(0,Math.min(1,(e-da.offset().left)/U)):(A=Math.max(0,Math.min(1,(e-da.offset().top)/U)),A=1-A);f();"undefined"!==typeof Q&&b.is('[class*="awp-tooltip"]')&&(b=aa?d-da.offset().left:g-da.offset().top,0>b?b=0:b>U&&(b=U),b=Math.max(0,Math.min(1,b/U)),aa||(b=1-b),b=parseInt(100*b,10),Q.volume(c.point,oa,b))}}).on("AWPTouchManager.MOUSE_MOVE",function(a,c){if(!k)return!1;var b=c.elem;a=c.e;var d=a.pageX,g=a.pageY;b.hasClass("awp-volume-seekbar")&&
"undefined"!==typeof Q&&b.is('[class*="awp-tooltip"]')&&(b=aa?d-da.offset().left:g-da.offset().top,0>b?b=0:b>U&&(b=U),b=Math.max(0,Math.min(1,b/U)),aa||(b=1-b),b=parseInt(100*b,10),Q.volume(a,oa,b))}).on("AWPTouchManager.MOUSE_LEAVE",function(a,b){if(!k)return!1;"undefined"!==typeof Q&&Q.hide()})}if(qa){var aa=oa.hasClass("awp-vertical")?!1:!0,Qa=.5,U=void 0!=t.volumeSize?t.volumeSize:aa?da.width():da.height();0>A?A=0:1<A&&(A=1);0!=A&&(Qa=A)}if(Mb)Ob.on("keyup.apnav",function(b){if(!k)return!1;var d=
b.keyCode;c(b.target);37==d?x.previousMedia():39==d?x.nextMedia():32==d?x.togglePlayback():77==d&&a()});var Cb=[r.find(".awp-next-toggle"),r.find(".awp-prev-toggle"),r.find(".awp-playlist-toggle"),r.find(".awp-share-item"),cb,pa,db,ja,ka],Pb=Cb.length,Na;for(Na=0;Na<Pb;Na++){var Qb=c(Cb[Na]).css("cursor","pointer").on("click",q);if(!va)Qb.on("mouseenter",u).on("mouseleave",C)}var e=Object.create(WaveSurfer);e.init({container:La[0],backend:"MediaElement",interact:1,hideScrollbar:!0,waveColor:t.wavesurfer.waveColor,
progressColor:t.wavesurfer.progressColor,barWidth:t.wavesurfer.barWidth,cursorColor:t.wavesurfer.cursorColor,cursorWidth:t.wavesurfer.cursorWidth,height:t.wavesurfer.height});e.on("loading",function(a){a="Loading... "+a.toString()+"%";ta.css("opacity",1).html(a)});e.on("finish",function(a){ub()});e.on("error",function(a){console.log(a)});e.on("audioprocess",function(a){a=e.getCurrentTime();var b=e.getDuration();wb&&(ya.html(AWPUtils.formatCurrentTime(a)),za.html(AWPUtils.formatDuration(b)));ea&&Ab.width(T.width()*
e.backend.getPlayedPercents());p.end&&a>=p.end&&ub()});e.on("play",function(){console.log('wavesurfer.on("play');Ma||(awpMediaStart(x,E,n.getCounter()),Ma=!0);db.find("i").removeClass("fa-play").addClass("fa-pause");P=!0;awpMediaPlay(x,E,n.getCounter())});e.on("pause",function(){xb();P=!1;awpMediaPause(x,E,n.getCounter())});e.on("seek",function(a){ea&&Ab.width(T.width()*a)});e.on("ready",function(){e.setVolume(A);var a=p.start||0;if(p.end)var b=p.end;p.playbackRate&&e.setPlaybackRate(p.playbackRate);
ha&&(b?e.play(a,b):e.play(a));ha=!0});e.on("waveform_ME_noPeaks",function(){if(Ua){var a=e.backend.getPeaks(900);a.length&&m(a,p.peakName||p.title);Ua=!1}ta.css("opacity",0);La.removeClass("awp-hidden").addClass("awp-visible");Da()});e.on("redraw",function(){Ca&&(ta.css("opacity",0),La.removeClass("awp-hidden").addClass("awp-visible"),Da(),Ca=!1)});this.getTitleFormatted=function(a,b){var c="",d=b||zb;"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?
"undefined"!==typeof a.artist||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(c=a.artist):c=a.title:c=a.artist+d+a.title;return c};Nb.resize(function(){if(!k)return!1;gb&&clearTimeout(gb);gb=setTimeout(x.resize,150);ea&&la.width(T.width())});x.resize=function(){e&&(e.drawer.containerWidth=e.drawer.container.clientWidth,e.drawBuffer(),P||e.drawer.updateProgress(e.backend.getPlayedPercents()))};this.loadPlayMedia=
function(){if(!k||!L||!p)return!1;p.mp3&&e.backend.peaks&&e.load(p.mp3,e.backend.peaks,!0);P=!0};this.playMedia=function(){if(!k||!L||P)return!1;"undefined"!==typeof e&&e.play();P=!0};this.pauseMedia=function(){if(!k||!L||!P)return!1;"undefined"!==typeof e&&e.pause();P=!1};this.checkMedia=function(a){if(!k||!L)return!1;a=a.toLowerCase();P&&"pause"==a&&("undefined"!==typeof e&&e.pause(),P=!1)};this.togglePlayback=function(){if(!k||!L)return!1;"undefined"!==typeof e&&(!Ma&&Ta&&e.backend.peaks?(ha=!0,
x.loadPlayMedia()):e.playPause())};this.stop=function(){if(!k||!L)return!1;"undefined"!==typeof e&&e.stop();P=!1};this.nextMedia=function(){if(!k||!O)return!1;n.advanceHandler(1,!0)};this.previousMedia=function(){if(!k||!O)return!1;n.advanceHandler(-1,!0)};this.loadMedia=function(a){if(!k||V||!O)return!1;if("undefined"===typeof a)return alert("loadMedia method requires either a track number or a track title to load. LoadMedia failed."),!1;if("string"===typeof a){var b;for(b=0;b<B;b++)if(a==G[b].data.title){a=
b;var c=!0;break}if(!c)return alert('Track with title "'+a+'" doesnt exist. LoadMedia failed.'),!1}else if("number"===typeof a){if(0>a||a>B-1)return alert('Invalid track number. Track number  "'+a+'" doesnt exist. LoadMedia failed.'),!1}else return alert("loadMedia method requires either a track number or a track title to load. LoadMedia failed."),!1;n.processPlaylistRequest(a)};this.loadPlaylist=function(a){if(!k||V)return!1;if("undefined"===typeof a||AWPUtils.isEmpty(a))return alert("loadPlaylist method requires id parameter. loadPlaylist failed."),
!1;if(na==a)return!1;na=a;w(na)};this.addTrack=function(a,b,d,e){if(!k||V)return!1;if("undefined"===typeof a)return alert("addTrack method requires format parameter. AddTrack failed."),!1;if("undefined"===typeof b)return alert("addTrack method requires track parameter. AddTrack failed."),!1;xa=!1;"undefined"!==typeof d&&(xa=d);d=1;var g=!1;if("string"!==typeof b&&"[object Object]"!==Object.prototype.toString.call(b))if("[object Array]"===Object.prototype.toString.call(b))d=b.length,g=!0;else return alert("addTrack method requires track as string, object or array parameter. AddTrack failed."),
!1;M=e;ma=!1;ca=!0;if(O)if("undefined"!==typeof M){if(0>M||M>B)return alert('Invalid position to insert track to. Position number "'+e+'" doesnt exist. AddTrack failed.'),!1;M==B&&(ma=!0)}else ma=!0,M=B;else{if("undefined"!==typeof M){if(0!=M)return alert('Invalid position to insert track to. Position number "'+e+'" doesnt exist. AddTrack failed.'),!1}else M=0;ma=!0}V=!0;lb();Fa=!1;Ya=!0;ba=-1;X=[];W=[];for(e=0;e<d;e++){var f=g?b[e]:b;if("html"==a){f=c(f);var l=c("<div>").append(f.clone()).html();
f=document.createElement("div");f.innerHTML=l;f=c(f.firstChild);f=y(f)}W.push(f)}B=W.length;wa=!1;O||(wa=!0);O=F;h()};this.inputAudio=function(a){if(!k||V)return!1;if("undefined"===typeof a)return alert("inputAudio method requires data parameter. inputAudio failed."),!1;v();n.reSetCounter();p=a;L="audio";void 0!=p.title&&eb(x.getTitleFormatted(p));va&&(ha=!0);I()};this.removeTrack=function(a){if(!k||V||!O)return!1;if("undefined"===typeof a)return alert("removeTrack method requires id parameter. removeTrack failed."),
!1;if("string"===typeof a){var b,c=!1;for(b=0;b<B;b++)if(a==G[b].data.title){a=b;c=!0;break}if(!c)return alert('Track with title "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else if("number"===typeof a){if(a=parseInt(a,10),0>a||a>B-1)return alert('Invalid id number. Track number  "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else return alert("removeTrack method requires either a id number or a track title to remove. removeTrack failed."),!1;G[a]?(F.children(".awp-playlist-item").eq(a).remove(),
G.splice(a,1),Pa(),0<B?(b=n.getCounter(),a==b?(Ka(),n.setPlaylistItems(B)):(n.setPlaylistItems(B,!1),a<b&&n.reSetCounter(n.getCounter()-1)),-1!=n.getCounter()?(Z=n.getCounter(),eb(Z)):awpMediaEmpty(x,E)):Wa()):alert('RemoveTrack with id "'+a+'" failed.')};this.sort=function(a,b){if(!k||!O)return!1;if("undefined"===typeof a)return console.log("Sort method requires type parameter. Sort method failed."),!1;var d=F.children("div.awp-playlist-item"),e=d.length,g=a.toLowerCase();if(2>e)return!1;if("title"==
g)for(AWPUtils.keysrt2(G,"data","title_full",b||!1),e=[],g=0;g<B;g++)e.push(G[g].id);else if("random"==g)e=AWPUtils.randomiseArray(e),G=AWPUtils.sortArray(G,e);else return console.log("Sort method requires type parameter. Sort method failed."),!1;g=n.getCounter();F.append(c.map(e,function(a){return d[a]}));-1!=g&&(e=F.children("div.awp-playlist-item[data-id='"+g+"']").index(),n.reSetCounter(e),Z=e);Pa()};this.destroyMedia=function(){if(!k)return!1;vb()};this.destroyPlaylist=function(){if(!k||!O)return!1;
Wa()};this.destroyPlugin=function(){if(!k)return!1;vb();"undefined"!==typeof e&&e.destroy()};this.setPlaybackRate=function(a){if(!k||"undefined"!==typeof n&&-1==n.getCounter())return!1;"undefined"!==typeof e&&e.setPlaybackRate(a)};this.toggleRandom=function(a){if(!k||"undefined"===typeof n)return!1;S="undefined"!==typeof a?a:!S;n.setRandom(S);S?ka.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):ka.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")};
this.toggleLoop=function(a){if(!k||"undefined"===typeof n)return!1;R="undefined"!==typeof a?a:!R;n.setLooping(R);R?ja.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):ja.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")};this.setVolume=function(a){if(!k)return!1;0>a?a=0:1<a&&(a=1);A=a;f()};this.getVolume=function(){return k?A:!1};this.toggleMute=function(){if(!k)return!1;a()};this.seek=function(a){if(!k||!L)return!1;"undefined"!==typeof e&&e.seekTo(a/
e.getDuration())};this.getCurrentTime=function(){if(!k||!L)return!1;var a;"undefined"!==typeof e&&(a=e.getCurrentTime());return a};this.getDuration=function(){if(!k||!L)return!1;var a;"undefined"!==typeof e&&(a=e.getDuration());return a};this.initPlaylistScroll=function(a){if(!k)return!1;ib(a)};this.destroyPlaylistScroll=function(){if(!k)return!1;ia.mCustomScrollbar("destroy");Ia=!1};this.updatePlaylistScroll=function(){if(!k)return!1;ia.mCustomScrollbar("update")};this.setAutoPlay=function(a){if(!k)return!1;
ha=a};this.getSetupDone=function(){return k};this.getPlaylistTransition=function(){return V};this.getPlaylistLoaded=function(){return Fa};this.getMediaPlaying=function(){return k?P:!1};this.getActiveItemId=function(){return k?"undefined"!==typeof n?n.getCounter():null:!1};this.getPlaylistLength=function(){return k?AWPUtils.isNumber(B)?B:0:!1};this.getPlaylistItems=function(){if(!k)return!1;var a=[];F.find("div.awp-playlist-item").each(function(){a.push(c(this))});return a};this.getPlaylistData=function(){return G||
null};this.getCurrMediaData=function(){return k?p:!1};this.getTitle=function(a){return ra(a)};this.getSettings=function(){return k?t||null:!1};this.getInstanceName=function(){return k?E:!1};this.toggleInteraction=function(){"undefined"!==typeof e&&e.toggleInteraction()};this.overControls=function(a){u(a)};this.outControls=function(a){C(a)};this.showPlayerElements2=function(){showPlayerElements2()};AWPUtils.isEmpty(na)?qb():w(na);return this}})(jQuery);